require 'Task::Catalyst'
require 'Catalyst::Helper'
require 'Catalyst::Devel'
require 'DBIx::Class::Schema::Loader'
require 'DBD::SQLite'
require 'Catalyst::Model::DBIC::Schema'
require 'JSON'
require 'Data::Printer'
